[package]
name = "gpt-model"
version = "0.1.0"
edition = "2021"

[features]
default = []
schemars = ["dep:schemars"]

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
schemars = { version = "0.8", optional = true }
