[package]
name = "gptcl-hyper"
version = "0.1.0"
edition = "2021"

[dependencies]
gptcl = { path = "../gptcl" }
hyper = { version = "0.14", features = ["client", "http1", "http2"] }
hyper-tls = "0.5"
